version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: store_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    container_name: store_redis
  
  web:
    build: .
    container_name: store_api
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - mongo
      - redis
    environment:
      MONGODB_URI: mongodb://mongo:27017/store_development
      REDIS_URL: redis://redis:6379/0

  test:
    build: .
    container_name: store_test
    command: bundle exec rspec
    volumes:
      - .:/rails
    depends_on:
      - mongo
      - redis
    environment:
      MONGODB_URI: mongodb://mongo:27017/store_test
      REDIS_URL: redis://redis:6379/1
      RAILS_ENV: test

volumes:
  mongo_data:
