:concurrency: 3
:timeout: 60
:verbose: true
:queues:
  - critical
  - default
  - mailers

:scheduler:
  :enabled: true
  :schedule:
    carts_cleanup:
      cron: "* * * * *"   # a cada minuto, para teste
      class: "Carts::CleanupJob"
      queue: default